### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by MrksKwsnck** [fcambus/ansiweather#100]
I'm working in a Cygwin Shell on a Windows 7 System behind a proxy. Running `./ansiweather` results in the following error:

    ERROR : Cannot fetch weather data

It seems there are not options to pass proxy settings. So I suggest to evaluate the environment variables `HTTP_PROXY` and `HTTPS_PROXY`.

**Comment by fcambus** [comment]
I'm closing this issue because I'm not sure what value it would add to the project - as it is something I would not personally use.
