### ISSUE TITLE
default and config outputs mutually exclusive?

### ISSUE THREAD

**Issue by resistor4u** [fcambus/ansiweather#101]
when running the command with default, i see the standard wind & temp & humidity data. when i rerun with my rc file, i get the options i've specified, but not the default info. are the two outputs mutually exclusive? i've opened up the code, but it might be above my skill level. is there a way to combine the two outputs, e.g.:

>`  Current weather in Yourtown => 76 °F ☔ - Wind => 3.89 mph SE - Humidity => 94 % - Pressure => 30.00 inHg`
>` Yourtown forecast =>`
>` Tue Aug 02: 80/74 °F ☔ `
>` Wed Aug 03: 80/74 °F ☁ `
>` Thu Aug 04: 82/74 °F ☁ `
>` Fri Aug 05: 84/73 °F ☔ `
>` Sat Aug 06: 90/77 °F ☔`

**Comment by JohnKacz** [comment]
I'm working on a pull request to add a bit more customization to the current weather output, but I believe what you are asking for is to have both the forecast data (which defaults to 5 days) and the current weather data (like wind, humidity, and pressure). So for example you'd like to see something like this:

```
Yourtown forecast =>
Tue Aug 02: 80/74 °F ☔ - Wind => 3.89 mph SE - Humidity => 94 % - Pressure => 30.00 inHg
Wed Aug 03: 80/74 °F ☁ - Wind => 3.89 mph E - Humidity => 90 % - Pressure => 31.00 inHg
Thu Aug 04: 82/74 °F ☁ - Wind => 3.89 mph SSE - Humidity => 87 % - Pressure => 30.00 inHg
Fri Aug 05: 84/73 °F ☔ - Wind => 3.89 mph ESE - Humidity => 92 % - Pressure => 29.00 inHg
Sat Aug 06: 90/77 °F ☔  - Wind => 3.89 mph SE - Humidity => 96 % - Pressure => 30.00 inHg
```

This is not possible nor would it make much sense. The API that is used, [OpenWeatherMap API](http://openweathermap.org/api), is able to give current information or forecasted information. The forecasted information does not include wind, humidity, or pressure. If you think about it that information would have to be a range and I'm not a weather geek but I think that info is not as predictable as high and low temperatures.

If I'm correct in what you are asking for and in the limitations of the OpenWeatherMap API then this issue could be closed I think.

**Comment by resistor4u** [comment]
Thanks for the response. As I tried to show in the hypothetical output, I'd like to receive the current data (showing all the measured observances) as well as the forecast of hi-lows. The program already shows one or the other, and I'd just like a default option to show both. I can't seem to control it from default RC file options, so I issued the request. And yes, it would be silly to have the program attempt to make accurate predictions even as the API doesn't. This is really an issue of trying to combine the fine-grained current data output with the forecast temps and conditions output. Current weather and forecast together.

**Comment by JohnKacz** [comment]
Ah I get it now. Sorry I misunderstood what you were asking. 

So one option would be you could just call it twice (`ansiweather && ansiweather -F`). 

It's not as elegant what you are asking for (something like `ansiweather -b` and in 'both'), but functionally I don't think it would be different as I think -b would still need to make to API calls. (The current data and the forecast are different endpoints)

**Comment by fcambus** [comment]
As JohnKacz pointed, you can achieve the desired effect with `ansiweather && ansiweather -F`, you can add a shell alias to perform this.
