### ISSUE TITLE
Readability: modify output colors

### ISSUE THREAD

**Issue by clstudio** [fcambus/ansiweather#104]
This tool is fantastic, but I struggle heavily reading the results, especially with the blue background.
Is there a possibility to modify the colors?

![screen shot 2016-10-24 at 1 54 55 pm](https://cloud.githubusercontent.com/assets/6853153/19644713/9a6a959c-99f1-11e6-977c-610f71048555.jpg)

I'd also like to mention that the following is no good solution for readability as well
```
-a value Toggle ANSI colors display ( true or false )
```

![screen shot 2016-10-24 at 4 12 18 pm](https://cloud.githubusercontent.com/assets/6853153/19649069/ac367bd4-9a04-11e6-9565-302c80c56f85.jpg)

It'd be best for readability if only the background disappeared instead of all the colors.

**Comment by fcambus** [comment]
You can customize output and colors by using a configuration file, you can find an example [here](https://github.com/fcambus/ansiweather/blob/master/ansiweatherrc.example).

**Comment by Eloitor** [comment]
I just had the same issue, and solved using "background:49m". I think this could be set as a default
