### ISSUE TITLE
Path Directory Separators?

### ISSUE THREAD

**Issue by PoLoMoTo** [fcambus/ansiweather#105]
Would it be possible to add an option to use symbols for the separation between directories in the current path?  I attached a screen shot that I found, I'm not sure how the look was achieved in the screen shot.
![687474703a2f2f7777772e67657870657274732e636f6d2f696d672f7465726d696e69782f7465726d696e697831312e706e67](https://cloud.githubusercontent.com/assets/5509894/20335654/4af8f172-ab92-11e6-9929-e901f772eecf.png)

(I apologize if this is already possible. I couldn't seem to find anything documenting this, although I didn't really know what to search.)

**Comment by fcambus** [comment]
Closing this has I don't see the link to AnsiWeather.

**Comment by PoLoMoTo** [comment]
Sorry, thats my bad. That what I get for having so many tabs open.
