### ISSUE TITLE
wind direction not customizable

### ISSUE THREAD

**Issue by emk2203** [fcambus/ansiweather#108]
If your language doesn't have the same convention that NESW are the directions, you need to change the script itself, which risks getting overwritten in a package update.

If line 240 where you set the wind directions is put into the `.ansiweatherrc` and pulled from there, it would be customizable as well.

Same goes for the replacement of the word 'forecast'.

**Comment by fcambus** [comment]
That makes sense, thanks for your suggestion.

Since version 1.08, you can also set "forecast_text" in `.ansiweatherrc`.
