### ISSUE TITLE
Switch to output forecast on new lines?

### ISSUE THREAD

**Issue by awarmfastbear** [fcambus/ansiweather#110]
Hey, I love this little app, would it be possible to add a simple switch that could display the output of each field on a new line?

**Comment by wlfgp** [comment]
You can do exactly that by your own with a little script:
```
#!/bin/sh
echo -e "\n" && \
     /home/path/to/ansiweather -l 123456 -d true|sed -e 's/--/\n/g' && \
    echo -e "\n"
```
Replace the location number 123456 with a location number from the list [here](http://openweathermap.org/help/city_list.txt).

You'll find an image of possible outputs [here](https://github.com/fcambus/ansiweather/issues/113).

And if you want you know how to change the colors of the output please note the [diff.txt](https://github.com/fcambus/ansiweather/files/1439727/diff.txt) mentioned on the previous page.

HTH

Regards,
Wolfgang

**Comment by vityav** [comment]
Can also just add this (with whatever colors you like) to the .ansiweatherrc:

    delimiter:\033[35m=>\n\r
    dashes:\033[34m\n\r

Results in:
![screenshot at 2018-06-27 15 07 46](https://user-images.githubusercontent.com/12485569/41994306-02f6c30e-7a1c-11e8-964d-fbff8bda7959.png)
