### ISSUE TITLE
Garbled output

### ISSUE THREAD

**Issue by wlfgp** [fcambus/ansiweather#113]
In the following please ignore the bold fonts: I didn't find an option to disable Markdown tags.

Pulled and used ansiweather version is from today, 2017-11-02

In the .ansiweather dir:
=====================================================
$ diff -u ansiweatherrc.example ~/.ansiweatherrc
--- ansiweatherrc.example	2017-11-02 14:06:30.357657188 +0100
+++ /home/[deleted-username]/.ansiweatherrc	2017-11-02 16:03:33.113102106 +0100
@@ -2,17 +2,17 @@
 
 api_key:85a4e3c55b73909f42c6a23ec35b7147
 fetch_cmd:curl -sf
-location:Rzeszow,PL
+location:Stuttgart,DE
 units:metric
 forecast:0
 ansi:true
-symbols:false
+symbols:true
 show_wind:true
-show_humidity:true
-show_pressure:true
-show_daylight:false
+show_humidity:false
+show_pressure:false
+show_daylight:true
 dateformat:%a %b %d
-timeformat:%b %d %r
+timeformat:%b %d %R
 
 # Text and Colors
 background:\\033[44m

========================

./ansiweather -l Rzeszow,PL -u metric -s false  -d true
\033[44m\033[36;1m Weather in Rzeszow \033[35m=>\033[33;1m 8 °C \033[34m-\033[36;1m Wind \033[35m=>\033[33;1m 9.8 m/s SW \033[34m-\033[36;1m Sunrise \033[35m=>\033[33;1m Nov 02 06:24 \033[34m-\033[36;1m Sunset \033[35m=>\033[33;1m Nov 02 16:05

or:
$ ./ansiweather -l Rzeszow,PL -u metric -s true -f 5 -d true
\033[44m\033[36;1m Rzeszow forecast \033[36;1m\033[35m=> \033[36;1mThu Nov 02: \033[33;1m8\033[36;1m/\033[33;1m7 °C \033[37;1m\xe2\x98\x94 \033[34m- \033[36;1mFri Nov 03: \033[33;1m8\033[36;1m/\033[33;1m7 °C \033[37;1m\xe2\x98\x94 \033[34m- \033[36;1mSat Nov 04: \033[33;1m10\033[36;1m/\033[33;1m5 °C \033[33;1m\xe2\x98\x80 \033[34m- \033[36;1mSun Nov 05: \033[33;1m9\033[36;1m/\033[33;1m5 °C \033[37;1m\xe2\x98\x81 \033[34m- \033[36;1mMon Nov 06: \033[33;1m9\033[36;1m/\033[33;1m3 °C \033[37;1m\xe2\x98\x94 
]$

or
./ansiweather -a false -l Rzeszow,PL -u metric -s true -f 5 -d true
\033[44m\033[36;1m Rzeszow forecast \033[36;1m\033[35m=> \033[36;1mThu Nov 02: \033[33;1m8\033[36;1m/\033[33;1m7 °C \033[37;1m\xe2\x98\x94 \033[34m- \033[36;1mFri Nov 03: \033[33;1m8\033[36;1m/\033[33;1m7 °C \033[37;1m\xe2\x98\x94 \033[34m- \033[36;1mSat Nov 04: \033[33;1m10\033[36;1m/\033[33;1m5 °C \033[33;1m\xe2\x98\x80 \033[34m- \033[36;1mSun Nov 05: \033[33;1m9\033[36;1m/\033[33;1m5 °C \033[37;1m\xe2\x98\x81 \033[34m- \033[36;1mMon Nov 06: \033[33;1m9\033[36;1m/\033[33;1m3 °C \033[37;1m\xe2\x98\x94 

]$ ./ansiweather -a false -l Rzeszow,PL -u metric -s false -f 5 -d true
\033[44m\033[36;1m Rzeszow forecast \033[36;1m\033[35m=> \033[36;1mThu Nov 02: \033[33;1m8\033[36;1m/\033[33;1m7 °C \033[34m- \033[36;1mFri Nov 03: \033[33;1m8\033[36;1m/\033[33;1m7 °C \033[34m- \033[36;1mSat Nov 04: \033[33;1m10\033[36;1m/\033[33;1m5 °C \033[34m- \033[36;1mSun Nov 05: \033[33;1m9\033[36;1m/\033[33;1m5 °C \033[34m- \033[36;1mMon Nov 06: \033[33;1m9\033[36;1m/\033[33;1m3 °C 
]$ 

This is happening on Fedora 26, linux 4.13.9-200.fc26.x86_64, GNOME Terminal 3.24.2, GNOME Shell 3.24.3.

Installed today:
jq-1.5-6.fc26.x86_64  
oniguruma-6.4.0-1.fc26.x86_64

I logged out of X/Gnome and in again after the the jq/oniguruma install. But didn't reboot.

bc.x86_64 version is 1.06.95-18.fc26 

And similar results as above with an xterm XTerm(327) on the same Gnome/Fedora environment.

HTH
Wolfgang

**Comment by fcambus** [comment]
Could you please try if the [1.11](https://github.com/fcambus/ansiweather/releases/tag/1.11) release exhibit the same issue?

**Comment by wlfgp** [comment]
1.11 works:
./ansiweather -l Rzeszow,PL -u metric -s false -f 5 -d true
![screenshot from 2017-11-02 17-40-48](https://user-images.githubusercontent.com/29075604/32338446-0e539100-bff5-11e7-8025-ead7ad2dc121.png)

./ansiweather -a true -l Rzeszow,PL -u metric -s true -f 5 -d true
![screenshot from 2017-11-02 with icons](https://user-images.githubusercontent.com/29075604/32338619-9b2fb9f0-bff5-11e7-84ba-1c20cbeb4335.png)

Thanks for the mega-fast response!

Regards
Wolfgang

**Comment by wlfgp** [comment]
@fcambus: *please* don't dig into this issue any farther:
after I installed 1.11, all of a sudden the recent version, that failed as mentioned initially, works too. And so far I have no idea why this is so, and what's going on ...

I hope to come back with more on this in a few hours, or at least ASAP

Regards
Wolfgang

**Comment by wlfgp** [comment]
OK, I think, and hope, I understand what was going on:

Short version first: after downloading 1.11 I _think_ I mistakenly copied and edited the  ansiweatherrc.example from 1.11 to my ~/.ansiweatherrc. I love that mistake!! ... :) Because it kept both versions running: 1.11 and the one I pulled  via something like
`git clone https://github.com/fcambus/ansiweather.git ~/.ansiweather` 
initially ..

The culprits for the garbled output in the git version from yesterday seem to be, IINM, the double backslashes in the ANSI tags in the very first pull ansiweatherrc.example.  The ansiweatherrc.example from 1.11 seems to be OK for both 1.11 and the latest git version. 

Please note a diff between my current ~/.ansiweatherrc and the latest git version ansiweatherrc.example I pulled yesterday:
[diff.txt](https://github.com/fcambus/ansiweather/files/1439727/diff.txt)

So the git version from yesterday works like a charm now:

I got the following result as shown in the screenshot below with this very long and - sorry - a little ugly one-liner:

`.ansiweather/ansiweather -l Stuttgart,DE -d true|sed 's/-/\n/g'; echo -e "\n"; .ansiweather/ansiweather -l Rzeszow,PL -d true|sed 's/-/\n/g';  sleep 2; echo -e "\n";.ansiweather/ansiweather -l Rzeszow,PL  -F|sed 's/=>/\n/g'|sed 's/-/\n/g'; echo -e "\n"; .ansiweather/ansiweather -l Stuttgart,DE  -F|sed 's/=>/\n/g'|sed 's/-/\n/g'; echo -e "\n... and the default one-liners:\n"; .ansiweather/ansiweather -l Rzeszow,PL; echo -e "\n"; .ansiweather/ansiweather -l Stuttgart,DE 
`
![long ansiweather list](https://user-images.githubusercontent.com/29075604/32356563-5466f574-c036-11e7-90a6-481351a97422.png)

Yes, I know - the output looks terrific .... :)

I've lifted parts of that one-liner from a German computer magazine, that recommeded ansiweather -- I still edited their ideas to get the result like in the image  above ... :)

**Comment by fcambus** [comment]
Thanks for testing and for your feedback, that's what I was suspecting indeed, because those were the only commits since 1.11 was released.

I just reverted the explicit escaping commits.

**Comment by wlfgp** [comment]
Great: The changed files seem to work out of the box - I just pulled them:
```
git clone https://github.com/fcambus/ansiweather.git .
```
Thanks for your work!
