### ISSUE TITLE
Multiple word cities used to work, now don't

### ISSUE THREAD

**Issue by drewx0r** [fcambus/ansiweather#114]
I used to use the following command to get the weather in New Orleans, Louisiana, USA:
`ansiweather -l New_Orleans,LA`

This now returns `ERROR: Cannot fetch weather data`

This error appears no matter what format I use (quotes, backslash to escape the space, US instead of LA, etc.)

I've used the openweathermap city ID as a workaround, but it's unfortunate that some variation of the actual city name can't be used for multi-word cities.

**Comment by wlfgp** [comment]
This at least works here:
`ansiweather -l New%20Orleans,US`

The ansiweather I used seems to be identical to one from Aug 30, 11:14, this year ...

**Comment by drewx0r** [comment]
Thanks! %20 works great. I'll use that in the future.

**Comment by wlfgp** [comment]
Welcome ... ;) - and it wasn't my idea: [here](https://github.com/fcambus/ansiweather/issues/4)'s more on it ...

**Comment by fcambus** [comment]
The API used to accept underscores to encode spaces in city names, and ansiweather converted spaces to underscores. Now that it doesn't work anymore, I switched to using '%20' instead in ff37c1c1bb6e77f811a6f6a79e73fa9510a0a514.

Thanks for reporting the issue.
