### ISSUE TITLE
ERROR: Cannot fetch weather data if there is no space

### ISSUE THREAD

**Issue by cmdcolin** [fcambus/ansiweather#116]
Hi there

I'm getting the error "ERROR: Cannot fetch weather data" if my location in my ansiweatherrc was location:Detroit,MI

I went out on a limb and added a space

location:Detroit, MI

and it worked. Not sure if you can document this or provide more error details or workaround? Thanks for the great tool :)

**Comment by fcambus** [comment]
Location format is city,CC where CC is a two-letter ISO 3166-1 alpha-2 country code.

So Detroit,US should work as intented.

**Comment by cmdcolin** [comment]
Sorry I guess the problem was that I did Detroit,MI (michigan) instead of Detroit,US
