### ISSUE TITLE
Whitespace on first line of output

### ISSUE THREAD

**Issue by cantab412** [fcambus/ansiweather#117]
Hi - 

When running ansiweather, I am getting a whitespace as the first character on the first line of output.

```
$ansiweather
 Weather in London  58 °F
Wind  11.41 mph E
Humd  67 %
Pres  30.21 inHg
SunR  May 18 05:03
SunS  May 18 20:51
```
Also, is there a way to override the "Weather in" text and just have "Temp" for the output?

Edit:  Bash 4.4.19 on Mac High Sierra, if that makes any difference.

**Comment by KharmaScribbles** [comment]
In your .ansiweatherrc file, change 

`greeting_text:Weather in`

to whatever you want.

Check out the ansiweatherrc.example file in this repo for more config options.

**Comment by cantab412** [comment]
I added ``greeting_text:`` to .ansiweatherrc and it did not change the behaviour at all.  Adding ``\n`` to the greeting_text did remove the location, but left the leading space before the location name.

Output after adding ``greeting_text``:

```
 Weather in Saffron Walden  76 °F
Wind  11.41 mph NE
Humd  33 %
Pres  30.03 inHg
SunR  Jul 03 04:45
SunS  Jul 03 21:21
```

Changing ``greeting_text`` to ``greeting_text:\n`` gives:

```
  Saffron Walden  76 °F
Wind  11.41 mph NE
Humd  33 %
Pres  30.03 inHg
SunR  Jul 03 04:45
SunS  Jul 03 21:21
```

**Comment by maxzinkus** [comment]
@cantab412 I created a pull with the minimal change. Can you make sure this is what you meant?

**Comment by maxzinkus** [comment]
(I still think this is a nicer default behavior, but, merging is up to you)
