### ISSUE TITLE
Dates in ISO-8601 format

### ISSUE THREAD

**Issue by xyproto** [fcambus/ansiweather#118]
Hi,

I'm trying to make ansiweather 1.12.0 on macOS output the time and date in an ISO-8601 compatible format.

On Linux, `date -I` can be used for outputting an ISO-8601 compatible time and date, but this is not supported on UNIX or macOS.

I tried the following in `~/.ansiweatherrc`:

    dateformat:%Y-%m-%d
    timeformat:%H:%M

(based on [this](https://stackoverflow.com/a/7216394/131264) stackoverflow answer).

The date looks right, but I am unable to see if the timeformat appears correctly.

Feature request: Could there be an option for only using ISO-8601 compatible time and dates?

Thanks for creating ansiweather.

Best regards,
Alexander F. Rødseth

**Comment by fcambus** [comment]
Hi,

Unfortunately, setting timeformat to `%H:%M` will not work because colons are used as separators when parsing the configuration file.

But this should work:

```
dateformat:%F
timeformat:%FT%T
```

You can test the timeformat display by issuing:

```
ansiweather -d true
```
