### ISSUE TITLE
ERROR: Cannot fetch weather data for the given location

### ISSUE THREAD

**Issue by mearleycf** [fcambus/ansiweather#120]
The file ~/.ansiweatherrc contains the following:

location:4256038
fetch_cmd:ftp -V -o -
units:imperial
show_daylight:true
forecast:5
symbols:true
show_humidity:true

And I get the error

ERROR: Cannot fetch weather data for the given location

**Comment by mearleycf** [comment]
Also, if I run:
```
➜ ansiweather -l 4256038 -u imperial -F -a true -s true -h true -d true
ERROR: Cannot fetch weather data for the given location
```
it returns the same error

**Comment by fcambus** [comment]
I cannot reproduce the issue. What system are you running ansiweather on?

**Comment by mearleycf** [comment]
Mac OSX iterm2 v3.0. I had it working until I configured the .ansiweatherrc file, then it stopped working. I just tested now, and when I empty the contents of ~/.ansiweatherrc file, it works again running the terminal command above on the first comment. The contents of the ansiweatherrc file that I emptied are above.

**Comment by mearleycf** [comment]
OSX mojave

**Comment by mearleycf** [comment]
running -->ftp does indeed open the ftp> prompt for me. I had to install FTP when I was first trying to get this to work. 
Like I said--it's working if I don't use the rc file.

**Comment by fcambus** [comment]
Updated README to stop mentioning that ftp can be used on Mac OS X, as it's apparently not the case anymore in Mojave.
