### ISSUE TITLE
Doesn't seem to match OpenWeatherMap data

### ISSUE THREAD

**Issue by kenahoo** [fcambus/ansiweather#128]
Not sure how this would happen, but the temperatures I'm seeing in my terminal:

```
% ansiweather -F -l Siren,US
 Siren forecast: Tue Jun 16: 80/66 °F ☁ - Wed Jun 17: 79/62 °F ☀ - Thu Jun 18: 76/62 °F ☔ - Fri Jun 19: 75/56 °F ☀ - Sat Jun 20: 65/54 °F ☔ 
```

don't seem to match what I see in the OpenWeatherMap web site at https://openweathermap.org/city/5273324:

<img width="552" alt="Screen Shot 2020-06-16 at 10 38 39 AM" src="https://user-images.githubusercontent.com/111939/84795897-ad561100-afbd-11ea-9f13-c1b6897e1da7.png">

And unfortunately neither of these are very consistent with weather.com's forecast (seen here through Google's results):

<img width="689" alt="Screen Shot 2020-06-16 at 10 42 15 AM" src="https://user-images.githubusercontent.com/111939/84796286-10e03e80-afbe-11ea-975c-490fb3603c75.png">

I would chalk this up to uncertainty, but a ten-degree discrepancy in the current day's forecast (it's 10:45 local time here, so the high is only a couple hours in the future) seems like quite a lot to just be model disagreement.  Maybe OpenWeatherMap is inconsistent with both itself and the real world right now?

**Comment by fcambus** [comment]
The discrepancy was/is quite huge indeed. Has it gotten better during the following days?
