### ISSUE TITLE
is this still working?

### ISSUE THREAD

**Issue by rafath** [fcambus/ansiweather#129]
```
./ansiweather -l Augustow -u metric -s true -k .... -i true -w true -h true -p true -d true
ERROR: Cannot fetch weather data
```
what could go wrong? where to check it?

**Comment by fcambus** [comment]
Is this with the default settings or are you using a configuration file?

**Comment by rafath** [comment]
thanks for reply, I've used your api key, instead of my private (freshly generated after creating an account) and it worked.
