### ISSUE TITLE
Change location in ansiweatherrc.example

### ISSUE THREAD

**Issue by p19pasc** [fcambus/ansiweather#130]
Hello, my name is Thomas and i am not used to github and cmd that much i need this nice tool for a project. I just need to change the default settings specifically the location. I open the ansiweatherrc.example with nano and type location:Corfu,GR and then save it. When i run the command `ansiweather` it just displays the default location again and not mine. Am i doing something wrong? (I just need to change the default settings in order not to use location -l command). 
Thank you!

**Comment by fcambus** [comment]
Please read the instructions in the [configuration](https://github.com/fcambus/ansiweather#configuration) section.

The easiest way is to rename the example configuration file to `.ansiweatherrc` and put it in your home directory.
