### ISSUE TITLE
You can install ansiweather with Awesome package manager

### ISSUE THREAD

**Issue by shinokada** [fcambus/ansiweather#132]
Hi, I created [Awesome package manager](https://github.com/shinokada/awesome) and I can install your repo using it.

After installing the Awesome:

```
awesome -i fcambus/ansiweather
# or 
awesome install fcambus/ansiweather
```

If you can put it in your README, it will be awesome.

Thanks.

Shin

**Comment by fcambus** [comment]
Thanks for the notification!
