### ISSUE TITLE
Feature Request: Feels like temperature

### ISSUE THREAD

**Issue by danrobi11** [fcambus/ansiweather#133]
Hello. (non-technical user here)

Is it possible to add the feels like temperature option?

The feels like temp is very important as that's how the weather really feels like outside.

If the weather is 27C and the humidity is 70%. The weather wont feel like 27C but more like 35C.

**Comment by fcambus** [comment]
Addressed by commit 73d080163e68a8c035baf943353b651dba44244a.

Thanks for raising the issue.

**Comment by danrobi11** [comment]
@fcambus Awesome! Thank you so much.

**Comment by danrobi11** [comment]
Something is not right about the `feels like` temp with `ansiweather`.

```
 Weather in Montreal: 73 °F - Feels like: 73 °F - UVI: 7.22 - Wind: 2.3 mph ESE - Humidity: 80% - Pressure: 29.82 inHg 
```
We can see here 73F with 80% humidity. The `feels like` is 73F. Thats impossible.

And that's the real `feels like` temp:

```
Montréal, QC Weather
Updated on Mon., Aug. 23, 8:15 a.m.
+ ADD TO MY LOCATIONS
75
°F
FEELS LIKE	86
```

The feels like in ansiweather is not the real `feels like` temp.

**Comment by fcambus** [comment]
AnsiWeather fetches weather data from [OpenWeatherMap](https://openweathermap.org).

**Comment by drewx0r** [comment]
@danrobi11 The previous pull request I made accidentally used a flag (`-h`) that was already being used for humidity. I don't know if that's what caused the incorrect readout. It shouldn't have. In any case, I have another pull request in that changes `-h` to `-H`. I tested it just now with Montreal and it did indeed give different results for temp vs. feels like (84 vs. 88 Fahrenheit with 57% humidity).

**Comment by danrobi11** [comment]
@fcambus 

> AnsiWeather fetches weather data from OpenWeatherMap

CLearly something is wrong with `OpenWeatherMap`. 22C with 88% humidity cant feels like 22C. And that should be obvious hence some is wrong with `OpenWeatherMap`.

22C with 88% humidity feels way more like 29C like it says here on `theweathernetwork.com`. I can confirm that from going outside. The `theweathernetwork.com` they also have an API. At least they provide proper information
