### ISSUE TITLE
Some options aren't working/aren't showing up

### ISSUE THREAD

**Issue by BCullen2201** [fcambus/ansiweather#139]
Here's what I typed into the terminal;

`ansiweather -l City, STATE -u imperial -a true -s true -i false -w true -h true -H true -p false -d false`

Units are still metric, Symbols didn't show up, Feels like didn't show up, Pressure showed up even though I set it to `false`

I'm using Linux Mint 20.2 XFCE

**Comment by fcambus** [comment]
This happens because you added a space between city and state.

Please try `ansiweather -l "City, STATE"` instead.

**Comment by BCullen2201** [comment]
Tried again with your suggestion, here's what I typed;
`ansiweather -l "City, STATE" -u imperial -a true -s true -i false -w true -h true -H true -p false -d false`

And this is the output;
`Illegal option -i`

I don't see a file named `.ansiweatherrc` anywhere in my home folder, do I need that for ansiweather to function properly?

**Comment by fcambus** [comment]
What version of ansiweather are you using?

The `.ansiweatherrc` file is not required, it's optional.

**Comment by BCullen2201** [comment]
AnsiWeather 1.11

**Comment by fcambus** [comment]
Support for fetching and displaying UV index was added in AnsiWeather 1.12.0, so yes that explains why you saw this error.
