### ISSUE TITLE
multiline output

### ISSUE THREAD

**Issue by Eloitor** [fcambus/ansiweather#140]
I would like to have the following output for `ansiweather -f 3`:
```
 Rzeszów forecast: 
- Fri Jul 15: 23/14 °C 
- Sat Jul 16: 23/11 °C 
- Sun Jul 17: 21/9 °C 
```

I tried using `dashes:\\n\033[34m-` in the config, but the output is:
```
 Rzeszów forecast: Fri Jul 15: 23/14 °C 
- Sat Jul 16: 23/11 °C 
- Sun Jul 17: 21/9 °C 
```

**Comment by Heistergand** [comment]
Try to set following in .ansiweatherrc:

forecast_text:forecast:\n\r
delimiter:\033[35m

This is a bit odd but works if you can live without delimiters.
