### ISSUE TITLE
Improve Forecast / Current Conditions

### ISSUE THREAD

**Issue by kerns** [fcambus/ansiweather#147]
Not sure if this is possible based on the available data – and maybe it is already available and I am just missing it. :)

But having an actual weather status beyond metrics would be most useful. For ex. "Sunny, Mostly Cloudy, Light Rain", etc... Temp, wind and pressure are interesting but don't really explain the consequences of weather for humans very well. (i.e. I need an umbrella, or I don't)

**Comment by kerns** [comment]
<img width="1426" alt="Screenshot 2023-01-30 at 11 38 19" src="https://user-images.githubusercontent.com/20254/215454445-81294e16-301b-461c-b83c-70e4a7e6d960.png">

The icons are really too small to be usable, so just having access to the underlying text or string that triggers them would solve my issue. :)

**Comment by kevinmatthes** [comment]
@kerns

I had the same issue regarding the icon size and solved it with the following workaround:

- Please create a configuration file for ansiweather in the correct scope (just your user account or the whole system).  There is a template to do so in this repository, https://github.com/fcambus/ansiweather/blob/master/ansiweatherrc.example.  For your account on a Linux system, save the example as `.ansiweatherrc` in your home directory.
- The icons (ll. 36) are strings which are displayed for the respective weather situation.  You can enter any text there which is going to be displayed, then.  The default string is the Unicode icon the template ships with.  For example, I altered the string for rain in my configuration from `rain:\033[37;1m\xe2\x98\x94` to `rain:\033[37;1m\xe2\x98\x94 (rainy)` such that now, after the icon the additional information "(rainy)" is shown.  Some terminals show rather large icons, so an additional information was my preferred solution.  The simplest way is to repeat the name of the weather situation, such as `rain:rain`, `snow:snow` and so on.

Does this suggestion solve the problem for you?

**Comment by kerns** [comment]
@kevinmatthes It could! Maybe I would just go with `rain: Rain` etc, as the icons are too small to be interpreted in my shell in any case. Thanks for the suggestion. 🙏
