### ISSUE TITLE
Multiple word city names do not display

### ISSUE THREAD

**Issue by dmanexe** [fcambus/ansiweather#154]
Issue: Full names (clipping from spaces) do not appear when you run, for example, San Francisco.

To reproduce: ansiweather -l San Francisco, CA

Output:
Weather in San => 32 °C - Wind => 3.84 m/s NNE - Humidity => 17 % - Pressure => 1011 hPa

**Comment by fcambus** [comment]
You need to quote the location as shown in the [example](https://github.com/fcambus/ansiweather#examples) from README and in the manual page.
