### ISSUE TITLE
ERROR: Cannot fetch weather data when using ansiweatherrc

### ISSUE THREAD

**Issue by thirota** [fcambus/ansiweather#157]
### Summary
Ansiweather script fails when using  the  config file.
```
% cat ~/.ansiweatherrc 
location:Tokyo

% ./ansiweather
ERROR: Cannot fetch weather data
```
### Environment
* macOS Sonoma
* AnsiWeather 1.19.0
### Expected behavior
Can fetch weather data.
### Actual behavior 
Cannot fetch weather data.
### Root cause
The location variable includes invalid text because the grep command marks up the matching text and returns the escape sequences.
### Workaround
* Easiest Solution 
Disable the grep color option like this.
```
% GREP_OPTIONS=--color=never
% ./ansiweather             
 Weather in Tokyo: 30 °C - UVI: 7.79 - Wind: 7.2 m/s S - Humidity: 70% - Pressure: 1012 hPa
```
* Another solution
Fix ansiweather script by adding the color option.
```
% git diff
diff --git a/ansiweather b/ansiweather
index 21ce381..8bbed76 100755
--- a/ansiweather
+++ b/ansiweather
@@ -32,7 +32,7 @@ get_config() {
        ret=""
        if [ -f "$config_file" ]
        then
-               ret=$(grep "^$1:" "$config_file" | cut -d: -f2-)
+               ret=$(grep "--color=never" "^$1:" "$config_file" | cut -d: -f2-)
        fi
 
        if [ "X$ret" = "X" ]
```

I would like to create a pull request, but I'm not sure whether the color option is available for every linux distribution. So, I will report this problem as an issue.

Thanks.

Taka

**Comment by chicks-net** [comment]
I'm on the same version of `ansiweather` and also on Sonoma and I don't have any issues.  I installed `ansiweather` via homebrew.  I tried your config file also:

```
% cat ~/.ansiweatherrc
location:Tokyo
```

and it worked for me.

```
 Weather in Tokyo: 28 °C - UVI: 7.69 - Wind: 3.6 m/s WSW - Humidity: 85% - Pressure: 1013 hPa
```

**Comment by thirota** [comment]
@chicks-net Thanks for your comment.

I apologize for the lack of explanation in the Environment section. I have an environment variable on my MacBook Air:
```
% env | grep GREP
GREP_OPTIONS=--color=always
```

On my other MacBook Pro, the ansiweather script works as expected, and it does not have `GREP_OPTIONS`.

This issue appears to depend on my local environment settings.

**Comment by chicks-net** [comment]
Thanks for explaining the `GREP_OPTIONS` issue again.  I missed that variable being set in the original issue.

It might be good for ansiweather to internally set `GREP_OPTIONS` to a value that isn't problematic.  It wouldn't override your usage of that option in the interactive shell.
