### ISSUE TITLE
Switch fetch_cmd default value to ftp?

### ISSUE THREAD

**Issue by fcambus** [fcambus/ansiweather#63]
ftp is available by default on *BSD systems and Mac OS X, so users of those systems only need 'jq' as a dependency. On Linux curl needs to be installed anyway so it would just mean switching dependency from curl to ftp.

Some testing should be done on all systems.

**Comment by lucc** [comment]
Are you trying to reduce the dependencies? If so I have an idea how to even remove the dependency on jq. We could use a shell file as a config file. [abcde](http://abcde.einval.com/wiki/) and [surfraw](http://surfraw.alioth.debian.org/) do it this way. The user then has to set shell variables in the config file.

If you want I can make a PR for this.

**Comment by fcambus** [comment]
Was mostly thinking out loud to see if it would make sense to replace the current default fetching program (curl) by ftp. But ftp CLI options differ on Linux, so that's probably a no go, as I do not want to add code to detect which OS is being used.

Regarding jq, it's not used to parse the configuration file, only for parsing API results for geolocation and weather. I'm fine with keeping it as a dependency as it allows to keep cleaner code and not use ugly regexpes hacks to parse API results.

**Comment by fcambus** [comment]
Leaving curl as default fetch method, closing.
