### ISSUE TITLE
City name returned by telize should be URL encoded when passed to openweathermap

### ISSUE THREAD

**Issue by henryso** [fcambus/ansiweather#71]
If the city name returned by telize has a space in it, the URL to connect to openweathermap is wrong and the result is unparseable by jq.  This also happens if the location name in .ansiweatherrc has a space in it.  For example, set location to "Sea Cliff,US".

**Comment by fcambus** [comment]
Thanks for reporting this, it should be an easy fix.

I will commit something soon.
