### ISSUE TITLE
Use Lat Long for weatherlookups

### ISSUE THREAD

**Issue by dfc** [fcambus/ansiweather#74]
The city list from weathermap contains a lot of duplicate city names, because they are in different states. This can lead to very strange results in the US and I imagine in other countries with duplicated city names. The telize api provides the latitude and longitude in the response and the openweathermap API also allows for queries to use lat/long instead of city id / city name. It would be nice if you used the lat/long instead of city names.

**Comment by fcambus** [comment]
The auto location feature was just an helper to try to guess user location in case no location is provided in the config file or when invoking the script. As you pointed out, it didn't work really well and querying for lat/long would have produced weird results when there is no city info for a given IP in the GeoIP database.

This feature is removed in 1.06, user location must now be explicitly set.
