### ISSUE TITLE
curl+ftp+wget?

### ISSUE THREAD

**Issue by Brigobet** [fcambus/ansiweather#75]
Hi, i am Brigo, the ansiweather Debian package maintainer.

The descriptions says ansiweather supports ftp, curl or wget, but it just support curl. It would be fine it support at least wget.
If not modify the Requirements section, Thanks. 

P.D. ansiweather is already in sid, i have 3 bug in few hours. :-D
https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=ansiweather;dist=unstable

**Comment by Brigobet** [comment]
Now i know why i get bug reports so fast: a post in planet.debian.org:
http://blog.alteholz.eu/2015/09/package-of-the-day-ansiweather/#comment-317

So you now should have a bunch of Debian users :)

**Comment by jwilk** [comment]
As far as I can see, the Requirements section is accurate.
The program uses curl by default, but it can be configured to use another download command:
https://github.com/fcambus/ansiweather/issues/75

**Comment by jwilk** [comment]
Oops, I meant this link:
https://github.com/fcambus/ansiweather#user-content-fetch-command

**Comment by fcambus** [comment]
Hi Brigo,

Once again, thanks for bringing ansiweather into the Debian packages collection :) Indeed, as @jwilk pointed, it default to curl but other fetching programs can be used via the configuration file.

For info, on OpenBSD the 'ftp' command is in base so the port patches ansiweather to use it by default, thus avoiding the port to depend on curl or wget : http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/astro/ansiweather/patches/patch-ansiweather?annotate=1.1.1.1

I think Debian used to install wget by default but not curl. If that's still the case maybe it could be a nice option to add a patch to replace curl by wget?

**Comment by Brigobet** [comment]
Why not detecting which one is installed? Just "if then else test":

 if /usr/bin/wget or /usr/bin/curl or usr/bin/ftp exist.



2015-09-23 0:05 GMT+02:00 Frederic Cambus <notifications@github.com>:

> Hi Brigo,
>
> Once again, thanks for bringing ansiweather into the Debian packages
> collection :) Indeed, as @jwilk <https://github.com/jwilk> pointed, it
> default to curl but other fetching programs can be used via the
> configuration file.
>
> For info, on OpenBSD the 'ftp' command is in base so the port patches
> ansiweather to use it by default, thus avoiding the port to depend on curl
> or wget :
> http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/astro/ansiweather/patches/patch-ansiweather?annotate=1.1.1.1
>
> I think Debian used to install wget by default but not curl. If that's
> still the case maybe it could be a nice option to add a patch to replace
> curl by wget?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fcambus/ansiweather/issues/75#issuecomment-142435566>.
>



-- 
Por limitaciones presupuestarias nos hemos visto obligados a apagar la luz
al final del túnel. Disculpen las molestias.

**Comment by jwilk** [comment]
Yes, in Debian wget's priority is `important`, which means it'll be installed by default.
curl's priority is only `optional`.

**Comment by krytarowski** [comment]
Please don't mess with guessing utilities on POSIX systems, neither `wget` nor `curl` are standard. You cannot guarantee that ftp works as excepted and accepts the set of guessed commands.

Please leave it as it is in a user configuration.

**Comment by fcambus** [comment]
Agreed, I'm going to leave this as it is, it's been working fine this way since the script was created two years ago.
