### ISSUE TITLE
have a switch so that the weather uses terms instead of symbols. 

### ISSUE THREAD

**Issue by shirishag75** [fcambus/ansiweather#77]
Hi all,
It would be nice if at the output used terms instead of symbol, this is useful and necessary both from accessibility viewpoint and sharing the content with others who might not have the symbol font/unicode at their end (I am guessing the symbol font is unicode-based).

**Comment by jwilk** [comment]
FYI, although undocumented, this is already configurable.
For example, I have this in my configuration file:
```
sun:[sun]
moon:[moon]
clouds:[clouds]
rain:[rain]
fog:[fog]
mist:[mist]
haze:[haze]
snow:[snow]
thunderstorm:[thunderstorm]
```

**Comment by shirishag75** [comment]
Hey @jwilk , 

how come you are here ;) .  Hmm.... where is this configuration file ? I searched quite a few places like . and .config and .local didn't see any . Even the man page doesn't tell anything about a configuration file.

**Comment by jwilk** [comment]
https://github.com/fcambus/ansiweather#user-content-configuration

Now I noticed there's also `ansiweatherrc.example`, which contains these items, so it's not completely undocumented.

**Comment by fcambus** [comment]
As @jwilk mentioned it's already possible to configure the display using a configuration file.

I'll make it more clear in the documentation and list the configuration variables names in the symbols section.

**Comment by thirota** [comment]
Hi @jwilk 
That example is very helpful.
Thanks!
