### ISSUE TITLE
get parse error: Invalid literal at line 1, column 4

### ISSUE THREAD

**Issue by shirishag75** [fcambus/ansiweather#80]
Hi all. 
Made the following .ansiweatherrc 

    location:Pune,IN
    fetch_cmd:ftp -V -o -
    symbols:false
    forecast:5
    #dateformat:%d-%m-%Y
    

I thought it's possible that the dateformat is malformed or something and that's why it wasn't working. 

This is the error it generates :-

    $ ansiweather
    parse error: Invalid literal at line 1, column 4
    ERROR : Cannot fetch weather data for the given location

**Comment by fcambus** [comment]
Are you running Debian? If so the ftp command packaged with Debian doesn't support the -V flag, this is likely what's causing the issue.

**Comment by shirishag75** [comment]
Actually it seems it doesn't even the like -o flag as well. At the end I just removed the entire fetch_cmd and it worked/works.

**Comment by sshaw** [comment]
> But what would be better is to have more meaningful error messages, if that's possible.

Yes, definitely. More clear docs too, I think. 

A fresh Homebrew install results in:
```
~/code/elisp/ruby-factory-mode >ansiweather -l Moscow,RU -u metric -s true -f 5 -d true
parse error: Invalid numeric literal at line 1, column 8
ERROR : Cannot fetch weather data for the given location
```
After rereading the docs and trying various thangz I run:
```
~/code/elisp/ruby-factory-mode >bash -x ansiweather -l Moscow,RU -u metric -s true -f 5 -d true
<snip extra bash expansion>
++ curl -s 'http://api.openweathermap.org/data/2.5/forecast/daily?q=Moscow,RU&units=metric'
+ weather='Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.'
+ '[' -z 'Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.' ']'
++ echo 'Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.'
++ jq -r .cod
parse error: Invalid numeric literal at line 1, column 8
+ status_code=
+ '[' '' '!=' 200 ']'
+ echo 'ERROR : Cannot fetch weather data for the given location'
ERROR : Cannot fetch weather data for the given location
```

The docs mention OpenWeatherMap, but not anything about an API key.

**Comment by sshaw** [comment]
See #82 and #83.
