### ISSUE TITLE
openweathermap.org requires an API key

### ISSUE THREAD

**Issue by woopla** [fcambus/ansiweather#82]
Hello,

As of today I could not get the weather, jq was outputting its cryptic `parse error: Invalid numeric literal at line 1, column 8` error message.

This is what curl is getting back from a call to http://api.openweathermap.org/data/2.5/weather?q=Fremont,CA,US&units=metric
> Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.

Looks like you need to register an API key now.

Thanks,

Clément

**Comment by sshaw** [comment]
@woopla I've submitted a pull request for this #84.

**Comment by sshaw** [comment]
I wonder if the popularity of this program drove them to require an API key? :computer: :arrow_right: :umbrella: = :closed_lock_with_key:

**Comment by jwilk** [comment]
http://openweathermap.org/faq#error401 reads:

> For FOSS developers: we welcome free software and are willing to help you. If you want to use OWM data in your free software application please register an API key and file a ticket describing your application and API key registered. OWM will review your request and grant immunity from usage limit overflow blocking.

It would be cool if ansiweather had its own key, so that it worked out of the box, instead of requiring every user to create an account.

**Comment by woopla** [comment]
@jwilk Yes I think that is the intended use case - ansiweather should get its own key and ask for 'immunity' - that terms seems like jail would be the case for people who infrige :)

**Comment by fcambus** [comment]
Merged @sshaw pull request, so there is now support for API keys.

Still pondering applying for immunity and if granted use it as default value.

**Comment by fcambus** [comment]
Here is an update regarding this issue, I just filled a request to get a global key for AnsiWeather. We'll see what the result is. Once I know the outcome, I'll tag a new version so the software can be updated in packages manager.

**Comment by fcambus** [comment]
AnsiWeather now has a FOSS key, there is no need for each user to register its own key anymore. I will likely tag 1.06 tomorrow.

**Comment by thirota** [comment]
Thanks!
