### ISSUE TITLE
Debian package is not present in Jessie

### ISSUE THREAD

**Issue by nocivus** [fcambus/ansiweather#91]
What the title says.

**Comment by Brigobet** [comment]
And it will never be. Onces a stable version is released no new packages
get into that release, just security updates or bug fixing updates.

It could get into Jessie anyhow using backports, but i doubt backports team
care enought for that script.

2016-03-15 17:10 GMT+01:00 Pedro <notifications@github.com>:

> What the title says.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/fcambus/ansiweather/issues/91
>



-- 
Por limitaciones presupuestarias nos hemos visto obligados a apagar la luz
al final del túnel. Disculpen las molestias.

**Comment by fcambus** [comment]
Thanks for the clarification, Brigo.
