### ISSUE TITLE
Multiple word city names do not return expected output

### ISSUE THREAD

**Issue by harrisongill** [fcambus/ansiweather#92]
You have to enter Los Angeles as losangeles to avoid this problem despite it being listed on the city page as "Los Angeles." Additionally entering cities as multiple words ignores the rest of the entry, defaulting the output to current weather (not forecast) and metric.

For example:

`ansiweather -l Los Angeles,US -u imperial -s true -f 5 -d true` gives the output ` Current weather in Kingdom of Sweden => 7 °C ☀ - Wind => 1.47 m/s NW - Humidity => 50 % - Pressure => 988 hPa 
` whereas `ansiweather -l losangeles,us -u imperial -s true -f 5 -d true` or `ansiweather -l "Los Angeles",us -u imperial -s true -f 5 -d true` (although the latter seems slower on my end) gives the output ` Los Angeles forecast => Sun Apr 10: 67/57 °F ☔ - Mon Apr 11: 66/52 °F ☔ - Tue Apr 12: 70/43 °F ☀ - Wed Apr 13: 68/44 °F ☀ - Thu Apr 14: 60/48 °F ☔ 
`.

Even if this is not fixed, it would be great if it could be better explained in the README.

**Comment by BlitzKraft** [comment]
It is an issue inherent with bash and getopts. They parse white spaces too. 

Instead of `los angeles` typing either `"los angeles"` or `los\ angeles` works fine.

**Comment by harrisongill** [comment]
Thanks @BlitzKraft, I will admit I am less familiar with the internal workings of bash and appreciate the explanation. It is what I was figuring but now I understand how to handle the white space.
