### ISSUE TITLE
ERROR : Cannot find jq binary

### ISSUE THREAD

**Issue by istrasci** [fcambus/ansiweather#99]
I'm on OSX, installed through Homebrew.  If I run from the command line, it works fine.  But if I put the command in my crontab, I get this error even though I do have `jq` installed.

Is this possibly an issue with where Homebrew installs binaries?  Why can't it find the `jq` binary?

**Comment by fcambus** [comment]
That's because the environment is different in both cases. Likely a PATH issue when cron calls the script.
